<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom Login CSS -->
    <link href="../css/login.css" rel="stylesheet">
    <!-- Toastr CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>
<style>
    .security-digits {
        font-size: 20px;
        font-weight: bold;
    }
 
    </style>
<body>
    <!-- Login Form Start -->
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
            <div class="header d-flex align-items-center mb-3">
                    <img src="../img/logo.webp" alt="Logo" class="logo me-3" />
                    <h2 class="fw-semi-bold">Institute of Personal Development Multan</h2>
                </div>  
                <h3 class="fw-semi-bold text-center">Login</h3>
                <form id="loginForm" action="login.php" method="post">
                    <div class="mb-3">
                        <label for="email" class="form-label">Email address</label>
                        <input type="email" class="form-control" name="email" placeholder="Enter your email" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" name="password" placeholder="Enter your password" required>
                    </div>

                    <!-- Security Question Generated by PHP -->
                    <div class="mb-3">
    <label for="security_question" class="form-label security_question">
        Solve the following: 
        <span class="security-digits">
            <?php
                // Generate random numbers for the security question
                $num1 = rand(1, 10);
                $num2 = rand(1, 10);

                // Store the numbers in session to validate on the server side
                session_start();
                $_SESSION['num1'] = $num1;
                $_SESSION['num2'] = $num2;

                // Display the question
                echo $num1 . " + " . $num2;
            ?>
        </span>
    </label>
    <input type="number" class="form-control" name="security_answer" placeholder="Your answer" required>
</div>

                    <div id="error-message" style="color: red; margin-top: 10px;"></div>

                    <button type="submit" class="btn btn-primary btn-lg w-100">Login</button>
                </form>
                <p>Don't have an account? <a href="../registration" class="text-primary">Register here</a></p>
            </div>
        </div>
    </div>
    <!-- Login Form End -->

    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Toastr JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        // Load error messages using AJAX
        window.onload = function() {
            loadErrorMessage(); // Load error/success messages when the page loads
        };

        // Function to load error message using AJAX
        function loadErrorMessage() {
            var xhr = new XMLHttpRequest();
            xhr.open('GET', 'get_error_message.php', true); // Make an AJAX request to fetch session messages
            xhr.onload = function() {
                if (xhr.status === 200) {
                    var response = JSON.parse(xhr.responseText);
                    
                    // Show error message via Toastr if exists
                    if (response.error) {
                        toastr.error(response.error);
                    }
                    
                    // Show success message via Toastr if exists (for future expansion)
                    if (response.success) {
                        toastr.success(response.success);
                    }
                }
            };
            xhr.send();
        }
    </script>
</body>
</html>
